# Travaux Dirigés n°1

## Configuration du notebook

In [1]:
import numpy as np
import scipy as sp

## Exercice 1

In [2]:
X = np.array([190., 172., 186., 180.]).reshape(-1, 1)
Y = np.array([112., 85., 135., 92.]).reshape(-1, 1)

In [3]:
def phi(X):
    ones = np.ones(X.shape[0]).reshape(-1, 1)
    return np.hstack((ones, X))

In [4]:
X_tilde = phi(X)

In [5]:
X_tilde.T @ X_tilde

array([[4.0000e+00, 7.2800e+02],
       [7.2800e+02, 1.3268e+05]])

In [6]:
np.linalg.det(X_tilde.T @ X_tilde)

np.float64(736.0000000000493)

In [7]:
beta_hat = np.linalg.inv(X_tilde.T @ X_tilde) @ X_tilde.T @ Y
beta_hat

array([[-291.63043478],
       [   2.18478261]])

In [8]:
Xi = np.array([188., 200.]).reshape(-1, 1)
Xi_tilde = phi(Xi)
Yi_hat = Xi_tilde @ beta_hat
Yi_hat

array([[119.10869565],
       [145.32608696]])

## Exercice 2

In [9]:
X = np.array([[2., 869.], [6., 581.], [10., 293.]])
Y = np.array([2., -23., -51.]).reshape(-1, 1)

In [10]:
X_tilde = phi(X)
X_tilde

array([[  1.,   2., 869.],
       [  1.,   6., 581.],
       [  1.,  10., 293.]])

In [11]:
X_tilde.T @ X_tilde

array([[3.000000e+00, 1.800000e+01, 1.743000e+03],
       [1.800000e+01, 1.400000e+02, 8.154000e+03],
       [1.743000e+03, 8.154000e+03, 1.178571e+06]])

In [12]:
np.linalg.det(X_tilde.T @ X_tilde)

np.float64(-2.7639543986879276e-08)

In [13]:
np.corrcoef(X, rowvar=False)

array([[ 1., -1.],
       [-1.,  1.]])

In [14]:
Z = X[:, [0]]
Z

array([[ 2.],
       [ 6.],
       [10.]])

In [15]:
Z_tilde = phi(Z)

In [16]:
beta_hat = np.linalg.inv(Z_tilde.T @ Z_tilde) @ Z_tilde.T @ Y
beta_hat

array([[15.75 ],
       [-6.625]])

In [17]:
Xi = np.array([0., 11.]).reshape(-1, 1)
Xi_tilde = phi(Xi)
Yi_hat = Xi_tilde @ beta_hat
Yi_hat

array([[ 15.75 ],
       [-57.125]])

## Exercice 3

In [18]:
X = np.array([[0.], [11.]])
Y = np.array([[15.], [-56.5]])

In [19]:
beta_hat = np.array([[15.],[(-56.5 - 15.)/(11. - 0.)]])
beta_hat

array([[15. ],
       [-6.5]])

In [20]:
X_tilde = phi(X)
X_tilde

array([[ 1.,  0.],
       [ 1., 11.]])

In [21]:
Q, R = np.linalg.qr(X_tilde)

In [22]:
Q, R

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([[-1.41421356, -7.77817459],
        [ 0.        ,  7.77817459]]))

In [23]:
Q[:,0] @ Q[:,1]

np.float64(-1.1102230246251565e-16)

In [24]:
Q.T @ Q

array([[ 1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00]])

In [25]:
Q @ R - X_tilde

array([[-3.33066907e-16, -1.77635684e-15],
       [ 0.00000000e+00, -1.77635684e-15]])

In [26]:
beta_hat = sp.linalg.solve_triangular(R, Q.T @ Y, lower=False)
beta_hat

array([[15. ],
       [-6.5]])