In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [3]:
1 / 6

0.16666666666666666

In [23]:
dieA = np.array([1, 1, 1, 1, 1, 1]) / 6.
dieB = np.array([1.75, 1.5, 1.25, 0.75, 0.5, 0.25]) / 6.

In [47]:
distA = sp.stats.multinomial(60, p=dieA)
distB = sp.stats.multinomial(60, p=dieB)

In [48]:
distA.rvs(1)

array([[ 7, 11, 12,  6, 11, 13]], dtype=int32)

In [53]:
distB.rvs(1)

array([[13, 19, 11, 13,  4,  0]], dtype=int32)

In [54]:
distA = sp.stats.multinomial(5, p=dieA)
distB = sp.stats.multinomial(5, p=dieB)

In [58]:
distB.rvs(1)

array([[2, 0, 1, 1, 0, 1]], dtype=int32)