# Travaux Dirigés n°3

## Configuration du notebook

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## Execice 3

In [14]:
def phi(X):
    return np.hstack((np.ones_like(X), X))

In [15]:
X = np.array([175., 181., 183., 189.]).reshape(-1, 1)
Y = np.array([95., 103., 101., 109.]).reshape(-1, 1)

In [16]:
X.mean(), X.std(), Y.mean(), Y.std()

(np.float64(182.0), np.float64(5.0), np.float64(102.0), np.float64(5.0))

In [17]:
Xs = (X - X.mean()) / X.std()
Xs

array([[-1.4],
       [-0.2],
       [ 0.2],
       [ 1.4]])

In [18]:
Ys = (Y - Y.mean()) / Y.std()
Ys

array([[-1.4],
       [ 0.2],
       [-0.2],
       [ 1.4]])

In [20]:
phi(Xs)

array([[ 1. , -1.4],
       [ 1. , -0.2],
       [ 1. ,  0.2],
       [ 1. ,  1.4]])

In [23]:
beta_hat = np.linalg.inv(phi(Xs).T @ phi(Xs)) @ phi(Xs).T @ Ys
beta_hat

array([[0.  ],
       [0.96]])

In [24]:
np.linalg.inv(phi(Xs).T @ phi(Xs))

array([[0.25, 0.  ],
       [0.  , 0.25]])